[package]
name = "rotten-probe"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "rottingapple-probe"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
hex = { workspace = true }
plist = { workspace = true }
rotten-core = { workspace = true }
rotten-discovery = { workspace = true }
rotten-pairing = { workspace = true }
rotten-protocol = { workspace = true }
tokio = { workspace = true }
